title: Barberena Mi Municipio
description: "De tishudos para tishudos. Entérate de todo lo que pasa en Barberena y El Cerinal: noticias, obras y el día a día de nuestra gente."
url: "https://barberenamimunicipio.top"
baseurl: ""

# Zona horaria oficial para Guatemala
timezone: America/Guatemala

# Le decimos a Jekyll que no use ningún tema predefinido,
# porque ya tenés tu propio diseño en styles.css
theme: null

# Que no procese estas carpetas/archivos como si fueran páginas
exclude:
  - README.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 10
paginate_path: "/blog/page:num/"

meses:
  - "Enero"
  - "Febrero"
  - "Marzo"
  - "Abril"
  - "Mayo"
  - "Junio"
  - "Julio"
  - "Agosto"
  - "Septiembre"
  - "Octubre"
  - "Noviembre"
  - "Diciembre"
  
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
