title: Barberena Mi Municipio
description: "Periodismo cívico hiperlocal en Barberena, Santa Rosa, Guatemala."
url: "https://barberenamimunicipio.github.io"

# Zona horaria oficial para Guatemala
timezone: America/Guatemala

# Le decimos a Jekyll que no use ningún tema predefinido,
# porque ya tenés tu propio diseño en styles.css
theme: null

# Que no procese estas carpetas/archivos como si fueran páginas
exclude:
  - README.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 10
paginate_path: "/blog/page:num/"

meses:
  - "Enero"
  - "Febrero"
  - "Marzo"
  - "Abril"
  - "Mayo"
  - "Junio"
  - "Julio"
  - "Agosto"
  - "Septiembre"
  - "Octubre"
  - "Noviembre"
  - "Diciembre"
